const aa = {
	"code": 200,
	"detailMsg": "\r\n{\"logBody\":\"{\\\"monthLastDay\\\":\\\"2025-12-31\\\",\\\"personId\\\":\\\"tN6H1ufWRnWmN1MyJrBTvoDvfe0=\\\"}\",\"logHeaders\":\"{\\\"Content-Type\\\":\\\"application/json\\\"}\",\"logQuery\":\"{\\\"serviceName\\\":\\\"getAttendanceDetailService\\\"}\",\"logUrl\":\"http://172.24.176.111:11033/econtract/api/osf\",\"responseData\":\"[{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-01\\\",\\\"dateType\\\":0,\\\"day\\\":1,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-02\\\",\\\"dateType\\\":0,\\\"day\\\":2,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-03\\\",\\\"dateType\\\":0,\\\"day\\\":3,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-04\\\",\\\"dateType\\\":0,\\\"day\\\":4,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-05\\\",\\\"dateType\\\":0,\\\"day\\\":5,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-06\\\",\\\"dateType\\\":1,\\\"day\\\":6,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":true,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":true,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-07\\\",\\\"dateType\\\":1,\\\"day\\\":7,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":true,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":true,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-08\\\",\\\"dateType\\\":0,\\\"day\\\":8,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-09\\\",\\\"dateType\\\":0,\\\"day\\\":9,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-10\\\",\\\"dateType\\\":0,\\\"day\\\":10,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-11\\\",\\\"dateType\\\":0,\\\"day\\\":11,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-12\\\",\\\"dateType\\\":0,\\\"day\\\":12,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-13\\\",\\\"dateType\\\":1,\\\"day\\\":13,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-14\\\",\\\"dateType\\\":1,\\\"day\\\":14,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-15\\\",\\\"dateType\\\":0,\\\"day\\\":15,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-16\\\",\\\"dateType\\\":0,\\\"day\\\":16,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-17\\\",\\\"dateType\\\":0,\\\"day\\\":17,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-18\\\",\\\"dateType\\\":0,\\\"day\\\":18,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-19\\\",\\\"dateType\\\":0,\\\"day\\\":19,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-20\\\",\\\"dateType\\\":1,\\\"day\\\":20,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-21\\\",\\\"dateType\\\":1,\\\"day\\\":21,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-22\\\",\\\"dateType\\\":0,\\\"day\\\":22,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-23\\\",\\\"dateType\\\":0,\\\"day\\\":23,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-24\\\",\\\"dateType\\\":0,\\\"day\\\":24,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-25\\\",\\\"dateType\\\":0,\\\"day\\\":25,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-26\\\",\\\"dateType\\\":0,\\\"day\\\":26,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-27\\\",\\\"dateType\\\":1,\\\"day\\\":27,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-28\\\",\\\"dateType\\\":1,\\\"day\\\":28,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-29\\\",\\\"dateType\\\":0,\\\"day\\\":29,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":true,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":true},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-30\\\",\\\"dateType\\\":0,\\\"day\\\":30,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false},{\\\"absence\\\":false,\\\"addSignIn\\\":false,\\\"attendDt\\\":1767196800000,\\\"attendDtShtStr\\\":\\\"2025-12-31\\\",\\\"dateType\\\":0,\\\"day\\\":31,\\\"early\\\":false,\\\"evection\\\":false,\\\"hasUnusual\\\":false,\\\"isAbsence\\\":false,\\\"isAddSignIn\\\":false,\\\"isEarly\\\":false,\\\"isEvection\\\":false,\\\"isLackCard\\\":false,\\\"isLate\\\":false,\\\"isOvertime\\\":false,\\\"isVacate\\\":false,\\\"lackCard\\\":false,\\\"late\\\":false,\\\"offsite\\\":false,\\\"otherOut\\\":false,\\\"outside\\\":false,\\\"overtime\\\":false,\\\"planWorkTime\\\":\\\"09:00-17:00\\\",\\\"scheduleShift\\\":false,\\\"sopport\\\":false,\\\"telecommute\\\":false,\\\"unusualWorkTime\\\":\\\"{begin: '', end: ''}\\\",\\\"vacate\\\":false}]\",\"responseHeaderData\":\"{}\",\"responseState\":\"200\",\"result\":\"1\",\"taskId\":\"2011253467439497217\",\"timeConsuming\":\"132\"}",
	"data": {
		"paramBody": "{\"monthLastDay\":\"2025-12-31\",\"personId\":\"tN6H1ufWRnWmN1MyJrBTvoDvfe0=\"}",
		"headers": {},
		"paramQuery": "{\"serviceName\":\"getAttendanceDetailService\"}",
		"body": "[{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-01\",\"dateType\":0,\"day\":1,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-02\",\"dateType\":0,\"day\":2,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-03\",\"dateType\":0,\"day\":3,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-04\",\"dateType\":0,\"day\":4,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-05\",\"dateType\":0,\"day\":5,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-06\",\"dateType\":1,\"day\":6,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":true,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":true,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-07\",\"dateType\":1,\"day\":7,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":true,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":true,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-08\",\"dateType\":0,\"day\":8,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-09\",\"dateType\":0,\"day\":9,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-10\",\"dateType\":0,\"day\":10,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-11\",\"dateType\":0,\"day\":11,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-12\",\"dateType\":0,\"day\":12,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-13\",\"dateType\":1,\"day\":13,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-14\",\"dateType\":1,\"day\":14,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-15\",\"dateType\":0,\"day\":15,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-16\",\"dateType\":0,\"day\":16,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-17\",\"dateType\":0,\"day\":17,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-18\",\"dateType\":0,\"day\":18,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-19\",\"dateType\":0,\"day\":19,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-20\",\"dateType\":1,\"day\":20,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-21\",\"dateType\":1,\"day\":21,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-22\",\"dateType\":0,\"day\":22,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-23\",\"dateType\":0,\"day\":23,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-24\",\"dateType\":0,\"day\":24,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-25\",\"dateType\":0,\"day\":25,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-26\",\"dateType\":0,\"day\":26,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-27\",\"dateType\":1,\"day\":27,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-28\",\"dateType\":1,\"day\":28,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-29\",\"dateType\":0,\"day\":29,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":true,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":true},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-30\",\"dateType\":0,\"day\":30,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false},{\"absence\":false,\"addSignIn\":false,\"attendDt\":1767196800000,\"attendDtShtStr\":\"2025-12-31\",\"dateType\":0,\"day\":31,\"early\":false,\"evection\":false,\"hasUnusual\":false,\"isAbsence\":false,\"isAddSignIn\":false,\"isEarly\":false,\"isEvection\":false,\"isLackCard\":false,\"isLate\":false,\"isOvertime\":false,\"isVacate\":false,\"lackCard\":false,\"late\":false,\"offsite\":false,\"otherOut\":false,\"outside\":false,\"overtime\":false,\"planWorkTime\":\"09:00-17:00\",\"scheduleShift\":false,\"sopport\":false,\"telecommute\":false,\"unusualWorkTime\":\"{begin: '', end: ''}\",\"vacate\":false}]",
		"statusCode": 200
	},
	"success": true,
	"hisId": "",
	"show": true,
	"message": "",
	"licenseSuccess": true,
	"status": "success"
}


const bb = [
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-01",
		"dateType": 0,
		"day": 1,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-02",
		"dateType": 0,
		"day": 2,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-03",
		"dateType": 0,
		"day": 3,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-04",
		"dateType": 0,
		"day": 4,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-05",
		"dateType": 0,
		"day": 5,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-06",
		"dateType": 1,
		"day": 6,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": true,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": true,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-07",
		"dateType": 1,
		"day": 7,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": true,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": true,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-08",
		"dateType": 0,
		"day": 8,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-09",
		"dateType": 0,
		"day": 9,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-10",
		"dateType": 0,
		"day": 10,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-11",
		"dateType": 0,
		"day": 11,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-12",
		"dateType": 0,
		"day": 12,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-13",
		"dateType": 1,
		"day": 13,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-14",
		"dateType": 1,
		"day": 14,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-15",
		"dateType": 0,
		"day": 15,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-16",
		"dateType": 0,
		"day": 16,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-17",
		"dateType": 0,
		"day": 17,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-18",
		"dateType": 0,
		"day": 18,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-19",
		"dateType": 0,
		"day": 19,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-20",
		"dateType": 1,
		"day": 20,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-21",
		"dateType": 1,
		"day": 21,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-22",
		"dateType": 0,
		"day": 22,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-23",
		"dateType": 0,
		"day": 23,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-24",
		"dateType": 0,
		"day": 24,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-25",
		"dateType": 0,
		"day": 25,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-26",
		"dateType": 0,
		"day": 26,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-27",
		"dateType": 1,
		"day": 27,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-28",
		"dateType": 1,
		"day": 28,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-29",
		"dateType": 0,
		"day": 29,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": true,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": true
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-30",
		"dateType": 0,
		"day": 30,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	},
	{
		"absence": false,
		"addSignIn": false,
		"attendDt": 1767196800000,
		"attendDtShtStr": "2025-12-31",
		"dateType": 0,
		"day": 31,
		"early": false,
		"evection": false,
		"hasUnusual": false,
		"isAbsence": false,
		"isAddSignIn": false,
		"isEarly": false,
		"isEvection": false,
		"isLackCard": false,
		"isLate": false,
		"isOvertime": false,
		"isVacate": false,
		"lackCard": false,
		"late": false,
		"offsite": false,
		"otherOut": false,
		"outside": false,
		"overtime": false,
		"planWorkTime": "09:00-17:00",
		"scheduleShift": false,
		"sopport": false,
		"telecommute": false,
		"unusualWorkTime": "{begin: '', end: ''}",
		"vacate": false
	}
]
